### ISSUE TITLE
Can't build latest commit

### ISSUE THREAD

**Issue by guillett** [openfisca/trace-tool#2]
I can't build that project.

I would like to leverage that work but I would appreciate a working base line.
This is the error I get:
```
ERROR in ./src/intl.jsx
Module not found: Error: Cannot resolve module 'intl/locale-data/json/fr-FR.json' in /repos/trace-tool/src
 @ ./src/intl.jsx 71:4-77:6
webpack: Failed to compile.
```

When I try to remove the internationalization I get
```
ERROR in Path must be a string. Received undefined
webpack: Failed to compile.
```

@cbenz I know some work is required to rely on the new API but the issue is somewhere else at the moment.
Do you have any pointer ?

Thanks.

**Comment by guillett** [comment]
Expert @Flightan, would you have any pointer on those issues ? 🙂

**Comment by cbenz** [comment]
Hi @guillett 

The error makes me think that the software relies on a specific version of the `intl` module, and hardcodes the path to the file `intl/locale-data/json/fr-FR.json`.

I think you may find the new place of `fr-FR.json` in a sub-directory of `node_modules/intl`, and update the source code accordingly.

And yes, the disclaimer: please note that this project is still a work in progress, and that since it has not been developed for months/years, it does certainly not work with the current version of the web API anymore.

**Comment by Flightan** [comment]
@guillett https://github.com/andyearnshaw/Intl.js/blob/master/README.md#intljs-and-browserifywebpack

**Comment by guillett** [comment]
I stopped trying to use that tool. Super-seeded by https://github.com/betagouv/openfisca-tracer
